apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: phasesecrets.secrets.phase.dev
spec:
  group: secrets.phase.dev
  names:
    kind: PhaseSecret
    listKind: PhaseSecretList
    plural: phasesecrets
    singular: phasesecret
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          description: PhaseSecret is the Schema for the phasesecrets API
          properties:
            apiVersion:
              description: APIVersion defines the versioned schema of this representation of an object.
              type: string
            kind:
              description: Kind is a string value representing the REST resource this object represents.
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: PhaseSecretSpec defines the desired state of PhaseSecret
              properties:
                phaseApp:
                  description: The Phase application name to fetch secrets from.
                  type: string
                phaseAppId:
                  description: The Phase application ID to fetch secrets from.
                  type: string
                phaseAppEnv:
                  description: The environment variable representing the app environment in Phase.
                  type: string
                  default: "production"
                phaseAppEnvPath:
                  description: Path within the Phase application environment to fetch secrets from.
                  type: string
                  default: "/"
                phaseAppEnvTag:
                  description: Tag for filtering secrets in the specified Phase app environment.
                  type: string
                authentication:
                  type: object
                  properties:
                    serviceToken:
                      type: object
                      required:
                        - serviceTokenSecretReference
                      properties:
                        serviceTokenSecretReference:
                          type: object
                          required:
                            - secretName
                            - secretNamespace
                          properties:
                            secretName:
                              description: The name of the Kubernetes Secret.
                              type: string
                            secretNamespace:
                              description: The namespace where the Kubernetes Secret is located.
                              type: string
                    kubernetesAuth:
                      type: object
                      required:
                        - phaseServiceAccountId
                        - serviceAccountRef
                      properties:
                        phaseServiceAccountId:
                          description: The service account ID in Phase.
                          type: string
                        serviceAccountRef:
                          type: object
                          required:
                            - name
                            - namespace
                          properties:
                            name:
                              description: The name of the Kubernetes ServiceAccount.
                              type: string
                            namespace:
                              description: The namespace of the Kubernetes ServiceAccount.
                              type: string
                phaseHost:
                  description: Phase host to pull secrets from.
                  type: string
                  default: "https://console.phase.dev"
                managedSecretReferences:
                  description: References to multiple managed Kubernetes Secrets.
                  type: array
                  items:
                    type: object
                    required:
                      - secretName
                      - secretNamespace
                      - secretType
                    properties:
                      secretName:
                        description: The name of the Kubernetes Secret.
                        type: string
                      secretNamespace:
                        description: The namespace where the Kubernetes Secret is located.
                        type: string
                      secretType:
                        description: The type of the Kubernetes Secret.
                        type: string
                        default: "Opaque"
                        enum:
                          - "Opaque"
                          - "kubernetes.io/tls"
                          - "kubernetes.io/service-account-token"
                          - "kubernetes.io/dockercfg"
                          - "kubernetes.io/dockerconfigjson"
                          - "kubernetes.io/basic-auth"
                          - "kubernetes.io/ssh-auth"
                          - "bootstrap.kubernetes.io/token"
                      processors:
                        description: Processors to transform the data during ingestion.
                        type: object
                        additionalProperties:
                          type: object
                          properties:
                            asName:
                              description: The mapped name of the field in the managed secret.
                              type: string
                            nameTransformer:
                              description: The format for transforming the secret key name.
                              type: string
                              enum:
                                - "camel"
                                - "upper-camel"
                                - "lower-snake"
                                - "tf-var"
                                - "dotnet-env"
                                - "lower-kebab"
                            type:
                              description: The type of process to be performed.
                              type: string
                              enum:
                                - "plain"
                                - "base64"
                              default: "plain"
                pollingInterval:
                  description: Interval at which to poll for secret updates.
                  type: integer
                  default: 60
              required:
                - phaseAppId
                - managedSecretReferences
                - phaseHost
            status:
              description: PhaseSecretStatus defines the observed state of PhaseSecret
              type: object
              properties:
                conditions:
                  description: Conditions representing the current state of the resource.
                  type: array
                  items:
                    type: object
                    required:
                      - lastTransitionTime
                      - message
                      - reason
                      - status
                      - type
                    properties:
                      lastTransitionTime:
                        description: Last time the condition transitioned from one status to another.
                        type: string
                        format: date-time
                      message:
                        description: Human-readable message indicating details about the transition.
                        type: string
                        maxLength: 32768
                      observedGeneration:
                        description: Generation that the condition was set based upon.
                        type: integer
                        format: int64
                        minimum: 0
                      reason:
                        description: Programmatic identifier for the reason of the condition's last transition.
                        type: string
                        maxLength: 1024
                        minLength: 1
                      status:
                        description: Status of the condition.
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      type:
                        description: Type of condition in CamelCase.
                        type: string
                        maxLength: 316
              required:
                - conditions
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
