apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phase-kubernetes-operator
rules:
  - apiGroups: ["secrets.phase.dev"]
    resources: ["phasesecrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: phase-kubernetes-operator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: phase-kubernetes-operator
  apiGroup: rbac.authorization.k8s.io
