apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phase.fullname" . }}-config
  labels:
    {{- include "phase.labels" . | nindent 4 }}
data:
  HOST: {{ .Values.global.host | quote }}
  HTTP_PROTOCOL: {{ .Values.global.httpProtocol | quote }}
  SSO_PROVIDERS: {{ .Values.sso.providers | quote }}
  DATABASE_HOST: {{ tpl .Values.database.host . | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  DATABASE_NAME: {{ .Values.database.name | quote }}
  DATABASE_USER: {{ .Values.database.user | quote }}
  REDIS_HOST: {{ tpl .Values.redis.host . | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  SESSION_COOKIE_DOMAIN: {{ .Values.global.host | quote }}
  {{- if .Values.license }}
  {{- if .Values.license.offline }}
  PHASE_LICENSE_OFFLINE: {{ .Values.license.offline | quote }}
  {{- end }}
  {{- end }}
