{{- if or (not .Values.global.external) (not .Values.redis.external) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phase.fullname" . }}-redis
  labels:
    {{- include "phase.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "phase.selectorLabels" . | nindent 6 }}
      app: redis
  template:
    metadata:
      labels:
        {{- include "phase.selectorLabels" . | nindent 8 }}
        app: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        args:
        {{- if .Values.secrets.redisPassword }}
        - --requirepass
        - $(REDIS_PASSWORD)
        {{- end }}
        env:
        {{- if .Values.secrets.redisPassword }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ required "**Error:** `phaseSecrets` is required. Set it in `values.yaml` or via `--set phaseSecrets=my-secret-name` to specify the Secret for Redis credentials." .Values.phaseSecrets }}
              key: REDIS_PASSWORD
        {{- end }}
        ports:
        - containerPort: {{ .Values.redis.service.port }}
        {{- if .Values.redis.readinessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.redis.service.port }}
          initialDelaySeconds: {{ .Values.redis.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.readinessProbe.periodSeconds }}
        {{- end }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 12 }}
{{- end }}
