apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phase.fullname" . }}-worker
  labels:
    {{- include "phase.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "phase.selectorLabels" . | nindent 6 }}
      app: worker
  template:
    metadata:
      labels:
        {{- include "phase.selectorLabels" . | nindent 8 }}
        app: worker
      annotations:
        # Wait for the migrations to complete
        batch.kubernetes.io/job-completion: "{{ include "phase.fullname" . }}-migrations"
    spec:
      initContainers:
      - name: wait-for-redis
        image: redis:alpine3.19
        command: ['sh', '-c', 
          'echo "Waiting for Redis at {{ tpl .Values.redis.host . }}:{{ .Values.redis.port }}...";
          {{- if .Values.secrets.redisPassword }}
          until redis-cli -h {{ tpl .Values.redis.host . }} -p {{ .Values.redis.port }} -a "$REDIS_PASSWORD" ping;
          {{- else }}
          until redis-cli -h {{ tpl .Values.redis.host . }} -p {{ .Values.redis.port }} ping;
          {{- end }}
          do echo "Redis is unavailable - sleeping 5s"; sleep 5; done;
          echo "Redis is ready!"']
        env:
        {{- if .Values.secrets.redisPassword }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "phase.fullname" . }}-secrets
              key: REDIS_PASSWORD
        {{- end }}
      containers:
      - name: worker
        image: "{{ .Values.global.images.backend.repository }}:{{ .Values.global.version }}"
        imagePullPolicy: {{ .Values.app.worker.image.pullPolicy }}
        command: ["python", "manage.py", "rqworker", "default"]
        envFrom:
        - configMapRef:
            name: {{ include "phase.fullname" . }}-config
        - secretRef:
            name: {{ include "phase.fullname" . }}-secrets
        env:
        - name: ALLOWED_HOSTS
          value: "$(HOST),{{ include "phase.fullname" . }}-worker"
        - name: ALLOWED_ORIGINS
          value: "$(HTTP_PROTOCOL)$(HOST)"
        - name: SESSION_COOKIE_DOMAIN
          value: "$(HOST)"
        resources:
          {{- toYaml .Values.app.worker.resources | nindent 12 }}
