apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "phase.fullname" . }}-migrations
  labels:
    {{- include "phase.labels" . | nindent 4 }}
    job-name: {{ include "phase.fullname" . }}-migrations
  annotations:
    # Migrations are run after all other resources (including PostgreSQL and Redis) are created and ready
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  backoffLimit: 6
  template:
    metadata:
      labels:
        {{- include "phase.selectorLabels" . | nindent 8 }}
        app: migrations
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-redis
        image: redis:alpine3.19
        command: ['sh', '-c', 'echo "Waiting for Redis at {{ tpl .Values.redis.host . }}:{{ .Values.redis.port }}..."; AUTH_ARGS=""; {{- if .Values.redis.user }} AUTH_ARGS="--user \"${REDIS_USER}\""; {{- end }} until redis-cli -h {{ tpl .Values.redis.host . }} -p {{ .Values.redis.port }}{{- if .Values.redis.ssl }} --tls{{- end }} $AUTH_ARGS -a "$REDIS_PASSWORD" ping 2>/dev/null || redis-cli -h {{ tpl .Values.redis.host . }} -p {{ .Values.redis.port }}{{- if .Values.redis.ssl }} --tls{{- end }} $AUTH_ARGS ping; do echo "Redis is unavailable - sleeping 5s"; sleep 5; done; echo "Redis is ready!"']
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ required "**Error:** `phaseSecrets` is required. Set it in `values.yaml` or via `--set phaseSecrets=my-secret-name` to specify the Secret for database credentials." .Values.phaseSecrets }}
              key: REDIS_PASSWORD
              optional: true
        {{- if .Values.redis.user }}
        - name: REDIS_USER
          value: {{ .Values.redis.user | quote }}
        {{- end }}
      - name: check-db-ready
        image: postgres:15.4-alpine3.17
        command: ['sh', '-c', 
          'echo "Waiting for database at {{ tpl .Values.database.host . }}:{{ .Values.database.port }}...";
          until pg_isready -h {{ tpl .Values.database.host . }} -p {{ .Values.database.port }} -U {{ .Values.database.user }} -t 5;
          do echo "Database is unavailable - sleeping 5s"; sleep 5; done;
          echo "Database is ready!"']
        # Set PGPASSWORD as DATABASE_PASSWORD
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ required "**Error:** `phaseSecrets` is required. Set it in `values.yaml` or via `--set phaseSecrets=my-secret-name` to specify the Secret for database credentials." .Values.phaseSecrets }}
              key: DATABASE_PASSWORD
        {{- if .Values.database.sslmode }}
        - name: PGSSLMODE
          value: {{ .Values.database.sslmode | quote }}
        {{- end }}
      containers:
      - name: migrations
        image: "{{ .Values.global.images.backend.repository }}:{{ .Values.global.version }}"
        imagePullPolicy: {{ .Values.app.backend.image.pullPolicy }}
        command: ["python", "manage.py", "migrate"]
        envFrom:
        - configMapRef:
            name: {{ include "phase.fullname" . }}-config
        - secretRef:
            name: {{ required "**Error:** `phaseSecrets` is required. Set it in `values.yaml` or via `--set phaseSecrets=my-secret-name` to specify the Secret for worker credentials." .Values.phaseSecrets }}
        env:
        - name: ALLOWED_HOSTS
          value: "$(HOST),{{ include "phase.fullname" . }}-worker"
        - name: ALLOWED_ORIGINS
          value: "$(HTTP_PROTOCOL)$(HOST)"
        - name: SESSION_COOKIE_DOMAIN
          value: "$(HOST)"
