apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phase.fullname" . }}-secrets
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.secrets.nextauthSecret | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  SERVER_SECRET: {{ .Values.secrets.serverSecret | quote }}
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  GOOGLE_OIDC_CLIENT_ID: {{ .Values.secrets.googleOidcClientId | quote }}
  GOOGLE_OIDC_CLIENT_SECRET: {{ .Values.secrets.googleOidcClientSecret | quote }}
  JUMPCLOUD_OIDC_CLIENT_ID: {{ .Values.secrets.jumpcloudOidcClientId | quote }}
  JUMPCLOUD_OIDC_CLIENT_SECRET: {{ .Values.secrets.jumpcloudOidcClientSecret | quote }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | quote }}
  GITLAB_CLIENT_ID: {{ .Values.secrets.gitlabClientId | quote }}
  GITLAB_CLIENT_SECRET: {{ .Values.secrets.gitlabClientSecret | quote }}
  GITLAB_AUTH_URL: {{ .Values.secrets.gitlabAuthUrl | quote }}
