apiVersion: v1
kind: Service
metadata:
  name: {{ include "phase.fullname" . }}-backend
  labels:
    {{- include "phase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.backend.service.type }}
  ports:
    - port: {{ .Values.app.backend.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "phase.selectorLabels" . | nindent 4 }}
    app: backend