apiVersion: v1
kind: Service
metadata:
  name: {{ include "phase.fullname" . }}-redis
  labels:
    {{- include "phase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      protocol: TCP
  selector:
    {{- include "phase.selectorLabels" . | nindent 4 }}
    app: redis