apiVersion: v1
kind: Service
metadata:
  name: {{ include "phase.fullname" . }}-postgres
  labels:
    {{- include "phase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    {{- include "phase.selectorLabels" . | nindent 4 }}
    app: postgres