apiVersion: v1
kind: Service
metadata:
  name: {{ include "phase.fullname" . }}-frontend
  labels:
    {{- include "phase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.frontend.service.type }}
  ports:
    - port: {{ .Values.app.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    {{- include "phase.selectorLabels" . | nindent 4 }}
    app: frontend