# Default values for phase-kubernetes-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: phasehq/kubernetes-operator
  tag: latest
  pullPolicy: IfNotPresent

# Security context for the operator pod
securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532

# Service account configuration
serviceAccount:
  create: true
  name: phase-kubernetes-operator

# RBAC settings
rbac:
  create: true

# Operator specific configuration
operator:
  logLevel: INFO
  env:
    PHASE_VERIFY_SSL: True
    PHASE_DEBUG: False
    PHASE_OPERATOR_HTTP_RETRIES: "5"
    PHASE_OPERATOR_HTTP_BACKOFF: "1"
    PHASE_OPERATOR_SOURCE_CACHE_TTL: "10"
    PHASE_OPERATOR_MAX_CONCURRENT_RECONCILES: "4"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
